# Cada cuantos ticks se generan las particulas (20 ticks = 1 segundo)
interval-ticks: 10
# Limites de seguridad para no matar el rendimiento / los clientes
max-density: 120
max-radius: 24
# En zonas con "dense true": da Velocidad I discreta para compensar que la Ceguera impide correr
dense-speed-boost: true
